import { Clock, Context, Duration, Effect, Ref } from 'effect'

export class DeviceCheckIOSJWTServiceEnvironment extends Context.Tag(
  '@identity-backend/auth/services/device-check/ios/jwt-service/DeviceCheckIOSJWTServiceEnvironment',
)<
  DeviceCheckIOSJWTServiceEnvironment,
  {
    /**
     * The Apple Developer Team ID associated with your iOS application.
     *
     * This identifies your development team in the Apple Developer ecosystem.
     * It must match the team ID that generated the DeviceCheck private key
     * and has the DeviceCheck capability enabled for your app bundle.
     *
     * Usage: Set as the issuer (iss) claim in the JWT payload
     */
    getTeamId: () => Effect.Effect<string>

    /**
     * The DeviceCheck Key ID for the private key used to sign JWTs.
     *
     * This identifier corresponds to a specific private key generated in your
     * Apple Developer account under "Certificates, Identifiers & Profiles" >
     * "Keys" with the "DeviceCheck" capability enabled.
     *
     * Usage: Set as the Key ID (kid) in the JWT header for signature verification
     */
    getKeyId: () => Effect.Effect<string>

    /**
     * The DeviceCheck private key for signing JWTs.
     *
     * This should be a pre-imported CryptoKey using the ES256 algorithm
     * (ECDSA with P-256 curve) as required by Apple's DeviceCheck API.
     *
     * Algorithm: ES256 (ECDSA with P-256 curve)
     * Usage: Used to cryptographically sign JWTs for DeviceCheck API authentication
     */
    getPrivateKey: () => Effect.Effect<CryptoKey>

    /**
     * The duration for which a newly generated JWT should be considered valid.
     *
     * This value determines the expiration time (exp claim) set on JWTs
     * generated by the service. Apple recommends short-lived tokens for
     * DeviceCheck API calls to minimize the impact of potential token leakage.
     *
     * Typical values: 5-15 minutes
     * Recommended: 10 minutes (600 seconds)
     * Impact: Sets the JWT expiration time (exp claim) and affects caching strategy
     */
    getJwtDuration: () => Effect.Effect<Duration.Duration>

    /**
     * The grace period before JWT expiration when the service should generate a new token.
     *
     * This value implements a proactive token refresh strategy to ensure fresh tokens
     * are always available for API calls. The service will generate a new token when
     * the current token's remaining validity falls below this threshold.
     *
     * Typical values: 30-60 seconds
     * Recommended: 30 seconds
     * Impact: Controls proactive token refresh to prevent expiration during API calls
     */
    getJwtCacheGracePeriod: () => Effect.Effect<Duration.Duration>
  }
>() {}

export class DeviceCheckIOSJWTService extends Effect.Service<DeviceCheckIOSJWTService>()(
  '@identity-backend/auth/services/device-check/ios/jwt-service/DeviceCheckIOSJWTService',
  {
    effect: Effect.gen(function*() {
      const { SignJWT } = yield* Effect.promise(() => import('jose'))
      const { addMinutes } = yield* Effect.promise(() => import('date-fns/addMinutes'))
      const { differenceInSeconds } = yield* Effect.promise(() => import('date-fns/differenceInSeconds'))

      const {
        teamId,
        keyId,
        privateKey,
        jwtDuration,
        jwtCacheGracePeriod,
      } = yield* DeviceCheckIOSJWTServiceEnvironment.pipe(
        Effect.andThen((env) =>
          Effect.all({
            teamId: env.getTeamId(),
            keyId: env.getKeyId(),
            privateKey: env.getPrivateKey(),
            jwtDuration: env.getJwtDuration(),
            jwtCacheGracePeriod: env.getJwtCacheGracePeriod(),
          })
        ),
      )

      const tokenCache = yield* Ref.make<{ token: string; exp: Date } | null>(null)

      const makeJWT = Effect.fn('device_check_ios.make_jwt')(function*() {
        const now = new Date(yield* Clock.currentTimeMillis)
        const exp = addMinutes(now, Duration.toMinutes(jwtDuration))

        const jwt = yield* Effect.promise(() =>
          new SignJWT({})
            .setProtectedHeader({
              alg: 'ES256',
              kid: keyId,
            })
            .setIssuer(teamId)
            .setIssuedAt(now)
            .setExpirationTime(exp)
            .sign(privateKey)
        )

        return { jwt, exp }
      })

      const getJWT = Effect.fn('device_check_ios.get_jwt')(function*() {
        const cached = yield* Ref.get(tokenCache)
        const now = new Date(yield* Clock.currentTimeMillis)

        if (cached && differenceInSeconds(cached.exp, now) > Duration.toSeconds(jwtCacheGracePeriod)) {
          return cached.token
        }

        const { jwt: token, exp } = yield* makeJWT()

        yield* Ref.set(tokenCache, { token, exp })

        return token
      })

      return {
        getJWT,
      }
    }),
  },
) {}
