/**
 * @module
 *
 * This module implements the "lite" username registration process as specified in the
 * "Polkadot mobile app v1 Release specification".
 *
 * "Lite" usernames are a key feature of the Polkadot mobile app's identity system. They are
 * designed to provide a user-friendly onboarding experience and grant access to free features
 * within the Polkadot ecosystem. The focus of this implementation is solely on "lite"
 * usernames; "full" username registration is not yet implemented.
 *
 * Key characteristics of "lite" usernames:
 * - **Unique Per Device:** Each "lite" username is tied to a unique device (iOS or Android) using
 *   Proof-of-Unique-Device (PoUD) provided by Apple and Google. This prevents a single user from
 *   registering multiple "lite" usernames from the same device.
 * - **Format:** Usernames follow the format `username.digits`, where the digits are generated by the
 *   system.
 * - **"Full" Username Reservation:** The first user to register a specific username (e.g., "anton")
 *   receives a 12-week reservation for the corresponding "full" username (e.g., "anton"). During
 *   this period, only they can upgrade their "lite" username to the "full" version. Note that the
 *   upgrade process to a "full" username is not part of the initial v1 release and is not
 *   implemented in this module.
 * - **Asynchronous Registration:** The on-chain registration of the username happens asynchronously.
 *   The user can continue with the app's onboarding process without waiting for the on-chain
 *   transaction to be finalized.
 * - **Chat Integration:** The user's `identifierKey` is a 65-byte uncompressed secp256k1 ECDH
 *   public key. It is the user's communication pubkey (`CommunicationIdentifier` in the
 *   individuality pallet) and is reused as the dotNS gateway `chat_key` — the same value is the
 *   `identifier_key` in the People-side consumer registration and the `chat_key` stored alongside
 *   the lite username on the dotNS contract.
 *
 * @see {@link module:apps/identity-backend/src/routes/v1/username/register/routes} for the implementation of the route.
 */
export * from './routes.js'
export * from './types.js'
